/*jshint esversion: 6 */

export const ADD_FLASH_MESSAGE="ADD_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE="DELETE_FLASH_MESSAGE";
export const SET_CURRENT_USER="SET_CURRENT_USER";

export const P_SET_PROJECTS="P_SET_PROJECTS";
export const P_SAVE_PROJECT="P_SAVE_PROJECT";
export const P_PROJECT_UPDATED="P_PROJECT_UPDATED";
export const P_PROJECT_FETCHED="P_PROJECT_FETCHED";
export const P_PROJECT_DELETED="P_PROJECT_DELETED";
